felleslosninger/tlp-organisation-chart

.github/workflows/release.yml

build: Add `pnpm` to release workflow

---

.changeset/small-hats-bathe.md
packages/org-chart/src/index.css
packages/org-chart/src/orgChart.ts

fix: Added prefix to all css-classes

---

.changeset/clever-numbers-travel.md
README.md
packages/org-chart/package.json
packages/org-chart/rollup.config.js
packages/org-chart/src/index.ts

build: Build files for es and cjs

---

.changeset/yellow-suns-smile.md
packages/org-chart/src/index.css

style: marking links

---

.changeset/yellow-carpets-grin.md
packages/org-chart/src/index.css
packages/org-chart/src/orgChart.ts

style: Set own stacking context for chart

---

.changeset/tiny-students-worry.md
packages/org-chart/src/orgChart.ts

fix: collect root children

---

packages/org-chart/src/index.css

style: wrap css in layer

---

.changeset/chilled-needles-report.md
apps/react/src/data/data11.json
apps/react/src/data/dataOffset1.json
apps/react/src/data/dataOffset2.json
packages/org-chart/src/index.css
packages/org-chart/src/orgChart.ts

1. resolves #47 
2. fixed arrow navigation when row only contains 1 column
3. corrected some test data files

fix: Connect center line and node lines, on last row, when row conatins two columns

---

.changeset/gold-elephants-wink.md
apps/react/src/data/digdir1.json
packages/org-chart/src/orgChart.ts
packages/org-chart/src/types/index.ts

feat: Add prefix to id's

---

packages/org-chart/src/index.css
packages/org-chart/src/orgChart.ts

style: wrap nodes in special column, to hide line

---

.changeset/hot-dots-smile.md
README.md
apps/storefront/app/routes/dokumentasjon.mdx
packages/org-chart/rollup.config.js
packages/org-chart/src/index.ts
packages/org-chart/src/types/index.ts

Adds a build for UMD
Fixes function attached to window
Updates documentation

build: Transpile to UMD

---

packages/org-chart/src/index.css
packages/org-chart/src/orgChart.ts

style: padding on inner nodes

---

apps/storefront/app/components/Chart/Chart.client.tsx
apps/storefront/app/components/Chart/Chart.module.css
apps/storefront/app/components/Chart/charts.ts
apps/storefront/app/data/avdelinger-og-seksjoner.json
apps/storefront/app/data/leveranseomrader.json

Updated the storefront with new and correct data. 
Implemented native select component from DS, to switch between different chart

fix: update storefront

---

packages/org-chart/src/index.css
packages/org-chart/src/orgChart.ts

Bugfix: layout provider function, and lines in tablet view

fix: layout provider bug

---

.changeset/great-games-tap.md
apps/react/src/components/Home/Home.tsx
apps/react/src/data/test.json
packages/org-chart/src/index.css
packages/org-chart/src/orgChart.ts

1. Fixed last row line, when it only contains one special column
2. Relocated focus visible from node to inner node.
3. Fixed arrow navigation on children nodes.
4. Removed tabindex 0 from achor nodes - achor should have default behavior

fix: multiple bux-fixes

---

.changeset/little-moons-invent.md
packages/org-chart/src/orgChart.ts

fix: home and end navigation

---

packages/org-chart/package.json

Ref browser key: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#browser

chore: Update package.json

---

apps/react/src/components/Home/Home.module.css
apps/react/src/components/Home/Home.tsx
apps/react/src/data/digdir3.json
packages/org-chart/src/index.css
packages/org-chart/src/orgChart.ts

Correct and adjust css with Designer.

style: Correct css against design

---

.changeset/proud-bugs-thank.md
apps/react/src/components/Home/Home.tsx
apps/react/src/data/test.json
packages/org-chart/src/index.css
packages/org-chart/src/orgChart.ts

Tested all combinations in org-chart. Maked sure that all lines works correct, and that arrow navigation work correct.
Fixed all the bugs i was able to find, and did a visual re-test on all combinations.

fix: test, locate and fix bugs in chart function

---

apps/storefront/app/components/PlaygroundGUI/PlaygroundGUI.client.tsx
apps/storefront/app/components/PlaygroundGUI/PlaygroundGUI.module.css
apps/storefront/app/components/ui/Header/Header.tsx
apps/storefront/app/data/short.json
apps/storefront/app/routes/playground.tsx
apps/storefront/package.json
pnpm-lock.yaml

Create a playground page (Lekeplass).
Implement a code editor, that can be used to code a JSON, and then be used to generate an org chart

feat: add playground to storefront

---

apps/storefront/app/routes/dokumentasjon.mdx

Updated documentation in md file for storefront. Can and should be copied to README. 
1. Complimented with more documentation about how to construct the JSON for org chart.
2. Updated old documentation

docs: update documentatation
